### ISSUE TITLE
WPE Crashes

### ISSUE THREAD

**Issue by IanKnighton** [secanis/uptime-robot-dashboard#1]
I've deployed this to a Pi Zero using Balena Cloud. The dashboard never loads. 

This is the output I'm seeing in the logs. 

```
22.01.20 12:26:14 (-0700)  app  >>>>> app               -  home-dashboard:1.1.0
22.01.20 12:26:14 (-0700)  app  >>>>> port              -  3000
22.01.20 12:26:14 (-0700)  app  >>>>> uptime robot key  -  xxxxxxx-xxxxxxxxxxxxxxxx
22.01.20 12:26:14 (-0700)  app  registering on wpe in   -  1000 ms
22.01.20 12:26:16 (-0700)  app  (node:1) UnhandledPromiseRejectionWarning: FetchError: request to http://wpe:8080/launch/ failed, reason: connect ECONNREFUSED 172.17.0.3:8080
22.01.20 12:26:16 (-0700)  app      at ClientRequest.<anonymous> (/usr/src/app/node_modules/node-fetch/lib/index.js:1455:11)
22.01.20 12:26:16 (-0700)  app      at ClientRequest.emit (events.js:198:13)
22.01.20 12:26:16 (-0700)  app      at Socket.socketErrorListener (_http_client.js:392:9)
22.01.20 12:26:16 (-0700)  app      at Socket.emit (events.js:198:13)
22.01.20 12:26:16 (-0700)  app      at emitErrorNT (internal/streams/destroy.js:91:8)
22.01.20 12:26:16 (-0700)  app      at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
22.01.20 12:26:16 (-0700)  app      at process._tickCallback (internal/process/next_tick.js:63:19)
22.01.20 12:26:16 (-0700)  app  (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
22.01.20 12:26:16 (-0700)  app  (node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
22.01.20 12:29:26 (-0700) Service exited 'wpe sha256:fe0463980a80bda6b71561019e2ec314c080d98a5d852fc340c4e5d862a001d2'
22.01.20 12:29:39 (-0700) Restarting service 'wpe sha256:fe0463980a80bda6b71561019e2ec314c080d98a5d852fc340c4e5d862a001d2'
22.01.20 12:29:45 (-0700) Service exited 'wpe sha256:fe0463980a80bda6b71561019e2ec314c080d98a5d852fc340c4e5d862a001d2'
22.01.20 12:30:00 (-0700) Restarting service 'wpe sha256:fe0463980a80bda6b71561019e2ec314c080d98a5d852fc340c4e5d862a001d2'
22.01.20 12:30:05 (-0700) Service exited 'wpe sha256:fe0463980a80bda6b71561019e2ec314c080d98a5d852fc340c4e5d862a001d2'
22.01.20 12:30:22 (-0700) Restarting service 'wpe sha256:fe0463980a80bda6b71561019e2ec314c080d98a5d852fc340c4e5d862a001d2'
22.01.20 12:30:29 (-0700) Service exited 'wpe sha256:fe0463980a80bda6b71561019e2ec314c080d98a5d852fc340c4e5d862a001d2'
22.01.20 12:30:56 (-0700) Restarting service 'wpe sha256:fe0463980a80bda6b71561019e2ec314c080d98a5d852fc340c4e5d862a001d2'
```
I believe I have everything configured correctly, but I can't seem to sort this part out.

**Comment by matthiasbaldi** [comment]
Ah yea, I had the same issue the last few days after my patches.
I switched to a newer wpe image yesterday  https://github.com/secanis/uptime-robot-dashboard/commit/7e53c3cdc61d47210dc5af52e6ba42406f00bcf2
Do you have used this new wpe image?

Try to rebuild the image/force push it to the balena cloud repository.

Edit: And what I forgot to write, you use a Pi Zero, I have only tested the project on a Raspi 3B

**Comment by IanKnighton** [comment]
I ended up wiping the SD card to try something else. 

I'll take another swing at it this weekend and see if that changes anything.

**Comment by matthiasbaldi** [comment]
Any News @IanKnighton ?  😉
